#basic tasks required for preparing the deployment environment
#  1. add deploy user
#  2. add package dependencies

- name: Ask for the new user password
  pause:
    prompt: "Enter the password for the new user"
  register: user_password

- name: Add deploy user
  user: 
        name: deploy
        password: "{{ user_password.user_input | password_hash('sha512') }}"
        groups:
          - sudo
        state: present
        shell: /bin/bash
        system: no
        create_home: yes
        home: /home/deploy

- name: install dependencies for rails app 
  apt: 
    name: '{{packages}}'
    state: present
  vars: 
    packages:
    
      - git-core 
      - curl 
      - zlib1g-dev
      - build-essential
      - libssl-dev
      - libreadline-dev
      - libyaml-dev
      - libsqlite3-dev
      - sqlite3
      - libxml2-dev
      - libxslt1-dev
      - libcurl4-openssl-dev
      - software-properties-common
      - libffi-dev
      - dirmngr
      - gnupg
      - apt-transport-https
      - ca-certificates
      - redis-server
      - redis-tools
      - acl #needed for running become on ubuntu 20

# nodejs 20 gives trouble for missing python2
# also gives warning of chart.js the engine pnpm appears to be invalid
# deployment fails
# need to revise packages required form node 20 and ruby 3.2
# try 18 for the moment and see how it works
- name: Installing Nodejs
  get_url:
    url: "https://deb.nodesource.com/setup_18.x"
    dest: ~/nodejs
    mode: 0755

- name: Nodejs Package
  command: ~/nodejs
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: Yarn GPG
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Importing Yarn Package
  copy:
    content: "deb https://dl.yarnpkg.com/debian/ stable main"
    dest: /etc/apt/sources.list.d/yarn.list

- name: Installing Nodejs + Yarn
  apt:
    name:
      - nodejs
      - yarn
    update_cache: true
