# run first, to add user and basic software for deploying rails app
---
- hosts: deployvmlocal
  become: true
  roles:
    - basic  # create user and install package dependencies
    - ruby   # install rbenv and ruby for the rails app
    - nginx # install and setup nginx and passenger for deploying app
    # postgresql # only run for setting up in production
