# run first, to add user and basic software for deploying rails app
---
- hosts: deployvmlocal
  become: true
  roles:
    - basic   # create user and install package dependencies
    - ruby    # install rbenv and ruby for the rails app
    - nginx   # install and setup nginx and passenger for deploying app
    - ssltest # enable and test SSL using self signed certificates
    - rotatelog # enable log rotation to prevent log overflow
    # - sslserve # enable SSL using certbot to handle certificates ***PRODUCTION***
    # - postgresql # only run for setting up in ***PRODUCTION***
